[package]
name = "tags"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "tags"

[dependencies]
hdk = { workspace = true }

serde = { workspace = true }

tags_integrity = { path = "../../integrity/tags", package = "tags_integrity" }
